# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/d/C++ Development/MCPPServerSoftware"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/d/C++ Development/MCPPServerSoftware"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/C++ Development/MCPPServerSoftware/CMakeFiles" "/mnt/d/C++ Development/MCPPServerSoftware//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/C++ Development/MCPPServerSoftware/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MCPPServerSoftware

# Build rule for target.
MCPPServerSoftware: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MCPPServerSoftware
.PHONY : MCPPServerSoftware

# fast build rule for target.
MCPPServerSoftware/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/build
.PHONY : MCPPServerSoftware/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/main.cpp.s
.PHONY : main.cpp.s

me/mskatking/mcppserversoftware/io/configs.o: me/mskatking/mcppserversoftware/io/configs.cpp.o
.PHONY : me/mskatking/mcppserversoftware/io/configs.o

# target to build an object file
me/mskatking/mcppserversoftware/io/configs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/configs.cpp.o
.PHONY : me/mskatking/mcppserversoftware/io/configs.cpp.o

me/mskatking/mcppserversoftware/io/configs.i: me/mskatking/mcppserversoftware/io/configs.cpp.i
.PHONY : me/mskatking/mcppserversoftware/io/configs.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/io/configs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/configs.cpp.i
.PHONY : me/mskatking/mcppserversoftware/io/configs.cpp.i

me/mskatking/mcppserversoftware/io/configs.s: me/mskatking/mcppserversoftware/io/configs.cpp.s
.PHONY : me/mskatking/mcppserversoftware/io/configs.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/io/configs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/configs.cpp.s
.PHONY : me/mskatking/mcppserversoftware/io/configs.cpp.s

me/mskatking/mcppserversoftware/io/json.o: me/mskatking/mcppserversoftware/io/json.cpp.o
.PHONY : me/mskatking/mcppserversoftware/io/json.o

# target to build an object file
me/mskatking/mcppserversoftware/io/json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/json.cpp.o
.PHONY : me/mskatking/mcppserversoftware/io/json.cpp.o

me/mskatking/mcppserversoftware/io/json.i: me/mskatking/mcppserversoftware/io/json.cpp.i
.PHONY : me/mskatking/mcppserversoftware/io/json.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/io/json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/json.cpp.i
.PHONY : me/mskatking/mcppserversoftware/io/json.cpp.i

me/mskatking/mcppserversoftware/io/json.s: me/mskatking/mcppserversoftware/io/json.cpp.s
.PHONY : me/mskatking/mcppserversoftware/io/json.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/io/json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/json.cpp.s
.PHONY : me/mskatking/mcppserversoftware/io/json.cpp.s

me/mskatking/mcppserversoftware/io/logger.o: me/mskatking/mcppserversoftware/io/logger.cpp.o
.PHONY : me/mskatking/mcppserversoftware/io/logger.o

# target to build an object file
me/mskatking/mcppserversoftware/io/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/logger.cpp.o
.PHONY : me/mskatking/mcppserversoftware/io/logger.cpp.o

me/mskatking/mcppserversoftware/io/logger.i: me/mskatking/mcppserversoftware/io/logger.cpp.i
.PHONY : me/mskatking/mcppserversoftware/io/logger.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/io/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/logger.cpp.i
.PHONY : me/mskatking/mcppserversoftware/io/logger.cpp.i

me/mskatking/mcppserversoftware/io/logger.s: me/mskatking/mcppserversoftware/io/logger.cpp.s
.PHONY : me/mskatking/mcppserversoftware/io/logger.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/io/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/io/logger.cpp.s
.PHONY : me/mskatking/mcppserversoftware/io/logger.cpp.s

me/mskatking/mcppserversoftware/networking/packets/packet.o: me/mskatking/mcppserversoftware/networking/packets/packet.cpp.o
.PHONY : me/mskatking/mcppserversoftware/networking/packets/packet.o

# target to build an object file
me/mskatking/mcppserversoftware/networking/packets/packet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/networking/packets/packet.cpp.o
.PHONY : me/mskatking/mcppserversoftware/networking/packets/packet.cpp.o

me/mskatking/mcppserversoftware/networking/packets/packet.i: me/mskatking/mcppserversoftware/networking/packets/packet.cpp.i
.PHONY : me/mskatking/mcppserversoftware/networking/packets/packet.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/networking/packets/packet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/networking/packets/packet.cpp.i
.PHONY : me/mskatking/mcppserversoftware/networking/packets/packet.cpp.i

me/mskatking/mcppserversoftware/networking/packets/packet.s: me/mskatking/mcppserversoftware/networking/packets/packet.cpp.s
.PHONY : me/mskatking/mcppserversoftware/networking/packets/packet.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/networking/packets/packet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/networking/packets/packet.cpp.s
.PHONY : me/mskatking/mcppserversoftware/networking/packets/packet.cpp.s

me/mskatking/mcppserversoftware/server/client.o: me/mskatking/mcppserversoftware/server/client.cpp.o
.PHONY : me/mskatking/mcppserversoftware/server/client.o

# target to build an object file
me/mskatking/mcppserversoftware/server/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/server/client.cpp.o
.PHONY : me/mskatking/mcppserversoftware/server/client.cpp.o

me/mskatking/mcppserversoftware/server/client.i: me/mskatking/mcppserversoftware/server/client.cpp.i
.PHONY : me/mskatking/mcppserversoftware/server/client.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/server/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/server/client.cpp.i
.PHONY : me/mskatking/mcppserversoftware/server/client.cpp.i

me/mskatking/mcppserversoftware/server/client.s: me/mskatking/mcppserversoftware/server/client.cpp.s
.PHONY : me/mskatking/mcppserversoftware/server/client.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/server/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/server/client.cpp.s
.PHONY : me/mskatking/mcppserversoftware/server/client.cpp.s

me/mskatking/mcppserversoftware/server/minecraft_server.o: me/mskatking/mcppserversoftware/server/minecraft_server.cpp.o
.PHONY : me/mskatking/mcppserversoftware/server/minecraft_server.o

# target to build an object file
me/mskatking/mcppserversoftware/server/minecraft_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/server/minecraft_server.cpp.o
.PHONY : me/mskatking/mcppserversoftware/server/minecraft_server.cpp.o

me/mskatking/mcppserversoftware/server/minecraft_server.i: me/mskatking/mcppserversoftware/server/minecraft_server.cpp.i
.PHONY : me/mskatking/mcppserversoftware/server/minecraft_server.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/server/minecraft_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/server/minecraft_server.cpp.i
.PHONY : me/mskatking/mcppserversoftware/server/minecraft_server.cpp.i

me/mskatking/mcppserversoftware/server/minecraft_server.s: me/mskatking/mcppserversoftware/server/minecraft_server.cpp.s
.PHONY : me/mskatking/mcppserversoftware/server/minecraft_server.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/server/minecraft_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/server/minecraft_server.cpp.s
.PHONY : me/mskatking/mcppserversoftware/server/minecraft_server.cpp.s

me/mskatking/mcppserversoftware/threads/thread_pool.o: me/mskatking/mcppserversoftware/threads/thread_pool.cpp.o
.PHONY : me/mskatking/mcppserversoftware/threads/thread_pool.o

# target to build an object file
me/mskatking/mcppserversoftware/threads/thread_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/threads/thread_pool.cpp.o
.PHONY : me/mskatking/mcppserversoftware/threads/thread_pool.cpp.o

me/mskatking/mcppserversoftware/threads/thread_pool.i: me/mskatking/mcppserversoftware/threads/thread_pool.cpp.i
.PHONY : me/mskatking/mcppserversoftware/threads/thread_pool.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/threads/thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/threads/thread_pool.cpp.i
.PHONY : me/mskatking/mcppserversoftware/threads/thread_pool.cpp.i

me/mskatking/mcppserversoftware/threads/thread_pool.s: me/mskatking/mcppserversoftware/threads/thread_pool.cpp.s
.PHONY : me/mskatking/mcppserversoftware/threads/thread_pool.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/threads/thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/threads/thread_pool.cpp.s
.PHONY : me/mskatking/mcppserversoftware/threads/thread_pool.cpp.s

me/mskatking/mcppserversoftware/util/component/text_components.o: me/mskatking/mcppserversoftware/util/component/text_components.cpp.o
.PHONY : me/mskatking/mcppserversoftware/util/component/text_components.o

# target to build an object file
me/mskatking/mcppserversoftware/util/component/text_components.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/util/component/text_components.cpp.o
.PHONY : me/mskatking/mcppserversoftware/util/component/text_components.cpp.o

me/mskatking/mcppserversoftware/util/component/text_components.i: me/mskatking/mcppserversoftware/util/component/text_components.cpp.i
.PHONY : me/mskatking/mcppserversoftware/util/component/text_components.i

# target to preprocess a source file
me/mskatking/mcppserversoftware/util/component/text_components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/util/component/text_components.cpp.i
.PHONY : me/mskatking/mcppserversoftware/util/component/text_components.cpp.i

me/mskatking/mcppserversoftware/util/component/text_components.s: me/mskatking/mcppserversoftware/util/component/text_components.cpp.s
.PHONY : me/mskatking/mcppserversoftware/util/component/text_components.s

# target to generate assembly for a file
me/mskatking/mcppserversoftware/util/component/text_components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServerSoftware.dir/build.make CMakeFiles/MCPPServerSoftware.dir/me/mskatking/mcppserversoftware/util/component/text_components.cpp.s
.PHONY : me/mskatking/mcppserversoftware/util/component/text_components.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MCPPServerSoftware"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... me/mskatking/mcppserversoftware/io/configs.o"
	@echo "... me/mskatking/mcppserversoftware/io/configs.i"
	@echo "... me/mskatking/mcppserversoftware/io/configs.s"
	@echo "... me/mskatking/mcppserversoftware/io/json.o"
	@echo "... me/mskatking/mcppserversoftware/io/json.i"
	@echo "... me/mskatking/mcppserversoftware/io/json.s"
	@echo "... me/mskatking/mcppserversoftware/io/logger.o"
	@echo "... me/mskatking/mcppserversoftware/io/logger.i"
	@echo "... me/mskatking/mcppserversoftware/io/logger.s"
	@echo "... me/mskatking/mcppserversoftware/networking/packets/packet.o"
	@echo "... me/mskatking/mcppserversoftware/networking/packets/packet.i"
	@echo "... me/mskatking/mcppserversoftware/networking/packets/packet.s"
	@echo "... me/mskatking/mcppserversoftware/server/client.o"
	@echo "... me/mskatking/mcppserversoftware/server/client.i"
	@echo "... me/mskatking/mcppserversoftware/server/client.s"
	@echo "... me/mskatking/mcppserversoftware/server/minecraft_server.o"
	@echo "... me/mskatking/mcppserversoftware/server/minecraft_server.i"
	@echo "... me/mskatking/mcppserversoftware/server/minecraft_server.s"
	@echo "... me/mskatking/mcppserversoftware/threads/thread_pool.o"
	@echo "... me/mskatking/mcppserversoftware/threads/thread_pool.i"
	@echo "... me/mskatking/mcppserversoftware/threads/thread_pool.s"
	@echo "... me/mskatking/mcppserversoftware/util/component/text_components.o"
	@echo "... me/mskatking/mcppserversoftware/util/component/text_components.i"
	@echo "... me/mskatking/mcppserversoftware/util/component/text_components.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

